version: "3.2"
services:
  app:
    build:
      context: .
    volumes:
      - ./dist:/var/www/html
      - ./000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - 8080:80
    links:
      - db
    depends_on:
      - db
  db:
    image: mysql:5.7
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
      - ./db/mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 43306:3306
